### ISSUE TITLE
Running within a Docker container

### ISSUE THREAD

**Issue by NoahTheDuke** [clojure-goes-fast/clj-async-profiler#26]
I'm trying to use this from within a leiningen process within a Docker container, and calling `prof/start!` threw this error:

```
[WARN] perf_event_open for TID 311 failed: Operation not permitted
[ERROR] No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1'
```

There's [this page](https://github.com/jvm-profiling-tools/async-profiler#profiling-java-in-a-container) from the jvm async-profiler, but I couldn't figure out how to apply those settings through `clj-async-profiler`.

Have any ideas?

**Comment by alexander-yakushev** [comment]
Hello Noah! What OS are you trying it on? Is it a container on the remote server or do you run it locally?

**Comment by NoahTheDuke** [comment]
I have Ubuntu 22.04, docker-compose 1.29.2, and I run it locally.

**Comment by alexander-yakushev** [comment]
[This link](https://github.com/jvm-profiling-tools/async-profiler#profiling-java-in-a-container) that you've pasted applies to clj-async-profiler just as well. For production usecase I remember crafting a special seccomp `profile.json` file that I passed to all Docker containers on the server. Since your case is a local one, I would start by trying passing this `--fdtransfer` flag to `docker run` or running the container with [unconstrained seccomp](https://docs.docker.com/engine/security/seccomp/#run-without-the-default-seccomp-profile). Please give it a try and tell how it goes.

**Comment by NoahTheDuke** [comment]
This worked out great. Thanks so much.
